name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu Version Details
        run: cat /etc/*release*
      - name: Tool versions
        run: |
          node -v
          npm -v
          python -v
          pip -v
          aws --version
          curl --version
      - name: python cmd> processor
        run: |
          import platform
          print(platform.processor())
        shell: python
          


